"""Core modules for GangDan Refined.

Foundation layer with zero business logic dependencies.
"""

from .config import (
    Config,
    CONFIG,
    CONFIG_FILE,
    DATA_DIR,
    DOCS_DIR,
    CHROMA_DIR,
    USER_KBS_FILE,
    ProxyConfig,
    LLMConfig,
    StorageConfig,
    SearchConfig,
    DocumentConfig,
    PreprintConfig,
    ResearchConfig,
    AdaptiveConfig,
    UIConfig,
    load_config,
    save_config,
    get_proxies,
    load_user_kbs,
    save_user_kb,
    delete_user_kb,
    sanitize_kb_name,
    detect_language,
    LANGUAGES,
    TRANSLATIONS,
    t,
)
from .constants import *
from .errors import (
    GangDanError,
    ConfigurationError,
    ValidationError,
    APIError,
    DatabaseError,
    FileError,
    TimeoutError,
    ModelError,
    ToolResult,
    ErrorContext,
    create_error_response,
)

__all__ = [
    "Config",
    "CONFIG",
    "CONFIG_FILE",
    "DATA_DIR",
    "DOCS_DIR",
    "CHROMA_DIR",
    "USER_KBS_FILE",
    "ProxyConfig",
    "LLMConfig",
    "StorageConfig",
    "SearchConfig",
    "DocumentConfig",
    "PreprintConfig",
    "ResearchConfig",
    "AdaptiveConfig",
    "UIConfig",
    "load_config",
    "save_config",
    "get_proxies",
    "load_user_kbs",
    "save_user_kb",
    "delete_user_kb",
    "sanitize_kb_name",
    "detect_language",
    "LANGUAGES",
    "TRANSLATIONS",
    "t",
    "GangDanError",
    "ConfigurationError",
    "ValidationError",
    "APIError",
    "DatabaseError",
    "FileError",
    "TimeoutError",
    "ModelError",
    "ToolResult",
    "ErrorContext",
    "create_error_response",
]